version: '3.4'

services:
  microserviceircore:
    image: ${DOCKER_REGISTRY-}microserviceircore
    build:
      context: .
      dockerfile: MicroserviceIrCore/Dockerfile


      docker run --name nginx -p 9090:80 -v /home/xiong/webapi/xnginx/nginx.conf:/etc/nginx/nginx.conf
