name: build and push docker hub

on:
  push:
    tags: 
    - 'v*'
env:
  IMAGE_NAME: sh17951/xiongwebapi
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: 1.checkout 
      uses: actions/checkout@v2
    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    
    #- name: build image
    #  run: docker build -t $IMAGE_NAME
    #- name: 2.Login to DockerHub
    #  run: |
    #    docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    #    tag=${GITHUB_REF:11}
    #    echo "Build Tag '$tag'"
    #    docker build -t sh17951/xiongwebapi:$tag .
    #    docker push sh17951/xiongwebapi:$tag
    #    #docker build -t xiongwebapi:v.1.0 .
    #    #docker tag xiongwebapi:v.1.0 sh17951/xiongwebapi:v.1.0
    #    #docker push sh17951/xiongwebapi:v.1.0
    
   
   
             
  
     
