name: Release

on:
  push:
    branches: [ master ]


env:
  IMAGE_NAME: xiongwebapi

jobs:
  push:
    runs-on: ubuntu-latest
    steps:

    - name: 1.checkout 
      uses: actions/checkout@v2
    
   

    - name: 5.executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      env:
        SHA: ${{ github.sha }}
        IMAGE_VERSION: ${{ github.ref }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
          echo "sha: $SHA"
          echo "version: $IMAGE_VERSION"
          IMAGE_ID=sh17951/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "$IMAGE_VERSION"| sed -e 's,.*/\(.*\),\1,')
          [[ "$IMAGE_VERSION" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          echo version = $IMAGE_VERSION
          ./abc sh17951/xiongwebapi:v.12.22.01
          
          
   
            
            
    #- name: build image
    #  run: docker build -t $IMAGE_NAME
    #- name: 2.Login to DockerHub
    #  run: |
    #    docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    #    tag=${GITHUB_REF:11}
    #    echo "Build Tag '$tag'"
    #    docker build -t sh17951/xiongwebapi:$tag .
    #    docker push sh17951/xiongwebapi:$tag
    #    #docker build -t xiongwebapi:v.1.0 .
    #    #docker tag xiongwebapi:v.1.0 sh17951/xiongwebapi:v.1.0
    #    #docker push sh17951/xiongwebapi:v.1.0
    
   
   
             
  
     
