name: build and push docker hub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 1.checkout 
      uses: actions/checkout@v2
    - name: sambaiz-test-docker-github-action
      # You may pin to the exact commit or the version.
      # uses: sambaiz/test-docker-github-action@5f162118833bef10815981309e18eb5a8903ea8c
      uses: sambaiz/test-docker-github-action@v1.0.1
      with: 
        # What do you say?
        i-say:  test name is 456 ${{ secrets.DOCKERHUB_USERNAME }} ,haha
    #-
    #    name: 2.Set up QEMU
    #    uses: docker/setup-qemu-action@v1
   # -
   #     name: 3.Set up Docker Buildx
   #     uses: docker/setup-buildx-action@v1
        
    #- name: 2.Setup dotnetcore 5.0
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 5.0.100
             
  
     
