name: build and push docker hub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 1.checkout 
      uses: actions/checkout@v2
      
    - name: 2.Setup dotnetcore 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
        
    - name: 3.dotnet build
      run: donnet build  01UserInterface\MicroserviceCodeTable/MicroserviceCodeTable.csproj -c release
      
    - name: 4.Docker Build & push to Docker Hub
      uses: opspresso/action-docker@master
      with:
        args: --dockder
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERFILE: "Dockerfile"
        IMAGE_NAME: "sh17951/xiongwebapi1"
        TAG_NAME: "v0.0.1"
        LATEST: "true"
     
