name: build and push docker hub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 1.checkout 
      uses: actions/checkout@v2
      
    - name: 2.Setup dotnetcore 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
        
    - name: dotnet build
      run: donnet build --c release
      
      
     
