name: Release

on:
  push:
    branches: [ master ]


env:
  IMAGE_NAME: xiongwebapi

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    
    - name: get version
      run: echo version = "${{ github.ref }}"

    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          ls -a
          echo "I am xiong" 
        host: "203.156.248.106"
        user: root
        key: ${{ secrets.PRIVATE_KEY}}
        port: 22222
            
            
    #- name: build image
    #  run: docker build -t $IMAGE_NAME
    #- name: 2.Login to DockerHub
    #  run: |
    #    docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    #    tag=${GITHUB_REF:11}
    #    echo "Build Tag '$tag'"
    #    docker build -t sh17951/xiongwebapi:$tag .
    #    docker push sh17951/xiongwebapi:$tag
    #    #docker build -t xiongwebapi:v.1.0 .
    #    #docker tag xiongwebapi:v.1.0 sh17951/xiongwebapi:v.1.0
    #    #docker push sh17951/xiongwebapi:v.1.0
    
   
   
             
  
     
